### ISSUE TITLE
Fails to build against imagemagick-7.0.7.19

### ISSUE THREAD

**Issue by seifertm** [utsushi/utsushi#48]
Utsushi-3.35.0 fails to build with the make switch `--with-magick` when imagemagick v7.0.7.19 is installed. The build exits with the following error:
```
doc-locate.cpp: In member function ‘Magick::Geometry {anonymous}::locator::cropdoc() const’:
doc-locate.cpp:265:25: error: ‘class Magick::Geometry’ has no member named ‘xNegative’
       if (clone.page ().xNegative ())
                         ^~~~~~~~~
doc-locate.cpp:269:25: error: ‘class Magick::Geometry’ has no member named ‘yNegative’
       if (clone.page ().yNegative ())
                         ^~~~~~~~~
make[3]: *** [Makefile:940: doc_locate-doc-locate.o] Error 1
```

The methods in question were removed in [this commit](https://github.com/ImageMagick/ImageMagick/commit/6e6af8ed20baf26aaf110518af6bca24f804cf86). This means that utsushi won't build with imagemagick>=7.0.1.

This is not a severe issue, but I feel that the build system should check that the correct version is installed. Other packagers will also be thankful for any hints on version requirements in the documentation. In the meantime, I will just use GraphicsMagick :)

**Comment by ghost** [comment]
Is it possible to port Utsushi to imagemagick7? Although imagemagick6 is still being maintained, I worry that one day it will be marked as end-of-life.

**Comment by paddy-hack** [comment]
> This is not a severe issue, but I feel that the build system should check that the correct version is installed.

It's hard to predict the future :wink:  Especially for ImageMagick.  GraphicsMagick is a good deal easier in that respect.  That said, I guess I could have added something when #43 was reported (but please note https://github.com/utsushi/utsushi/issues/43#issuecomment-355918321).

Anyway, if anyone is interested in porting to ImageMagick 7, see the last suggestion in https://github.com/utsushi/utsushi/issues/43#issuecomment-355918321.  Merge requests and patches are welcome.

**Comment by m1027** [comment]
> Anyway, if anyone is interested in porting to ImageMagick 7, see the last suggestion in #43 (comment). Merge requests and patches are welcome.

WFM, see #43.

**Comment by seifertm** [comment]
Sorry, when opening this issue, I didn't stumble upon #43 .

If supporting both ImageMagick and GraphicsMagick is becoming a maintenance burden, it might be worth considering to drop support of either library. Personally, I wouldn't mind. After all, both provide the same features as far as I understand.
